import React from 'react';
import Image from 'next/image';

const MessageBox: React.FC = () => {
  return (
    <div className='h-screen'>
        <div className="heading bg-gradient-to-tl to-[#cfad1f] from-[#93a877] flex p-7 items-center justify-center text-white gap-10">
            <div className="image"><Image src={'/chat-bot-img.png'} height={20} width={70} alt='chat-bot-image'/></div>
            <div>
                <h3 className='font-bold text-3xl'>Chat Support</h3>
                <p>Hi My name is Peace. How can I help you? </p>
            </div>
        </div>
        <div className="bg-[url('/nsuk-logo.png')] bg-center bg-cover bg-blend-overlay bg-opacity-60 bg-white h-4/6 overflow-scroll md:pb-20 p-3 flex flex-col gap-4 justify-end">
            {/* <div>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quae a id ratione reprehenderit eos corporis dolorum illum libero, commodi ducimus quo? Ut nesciunt perferendis alias esse pariatur nisi autem dicta velit dolor nam hic distinctio aperiam officiis enim, tempora, ratione quae voluptas voluptatum reiciendis! Commodi provident ratione nihil nesciunt unde, culpa nam vitae excepturi doloremque, distinctio numquam sint et fugiat voluptate blanditiis. Omnis earum distinctio animi accusantium sit, eum quae quibusdam, quam magnam, itaque obcaecati fugiat! Dolore repellat totam, iste laborum odit dolores esse, nostrum tempora doloremque quas ipsam debitis nam sunt commodi cupiditate molestiae consectetur rem, omnis voluptates deleniti ea asperiores? Tenetur vel repellendus enim porro repudiandae, incidunt quisquam. Soluta tenetur rem deleniti hic molestiae asperiores facilis nam recusandae veniam maxime, corporis quidem culpa odit, neque mollitia, doloribus vel delectus doloremque amet! Mollitia corporis libero a eum temporibus, earum assumenda iusto, ex itaque aut molestiae incidunt excepturi quos sequi provident, adipisci totam corrupti quasi reiciendis quisquam ut accusamus dolorum pariatur? Tenetur repellat porro officia. Consequuntur doloremque, error sequi minima aspernatur dolor vero ad deserunt, quisquam tenetur laudantium nulla at quos sunt quidem repudiandae voluptatum. Vel voluptatum sapiente corporis ipsa sunt, veniam odio nostrum excepturi fuga aspernatur ipsum itaque! Dolor eius eum, labore voluptate nulla nihil aliquid placeat enim tempore soluta maxime inventore illum nostrum? Commodi ut magnam laudantium doloribus enim fugiat alias vero. Dolorem quasi architecto tenetur, aperiam neque, velit ab quod sunt debitis laborum ipsum dignissimos sed? Itaque delectus aspernatur veniam voluptates sunt accusantium pariatur hic, iusto laudantium accusamus ratione quam, nulla quo mollitia, incidunt deleniti. Explicabo ipsum similique quis nisi incidunt laborum vero cum dolore eos et quo quasi ad voluptatibus, sunt reprehenderit odit provident asperiores perspiciatis consequatur, aut alias molestiae cumque rem error? Esse sint iste earum, maiores veritatis incidunt officiis delectus vero voluptatibus deleniti culpa?
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quae a id ratione reprehenderit eos corporis dolorum illum libero, commodi ducimus quo? Ut nesciunt perferendis alias esse pariatur nisi autem dicta velit dolor nam hic distinctio aperiam officiis enim, tempora, ratione quae voluptas voluptatum reiciendis! Commodi provident ratione nihil nesciunt unde, culpa nam vitae excepturi doloremque, distinctio numquam sint et fugiat voluptate blanditiis. Omnis earum distinctio animi accusantium sit, eum quae quibusdam, quam magnam, itaque obcaecati fugiat! Dolore repellat totam, iste laborum odit dolores esse, nostrum tempora doloremque quas ipsam debitis nam sunt commodi cupiditate molestiae consectetur rem, omnis voluptates deleniti ea asperiores? Tenetur vel repellendus enim porro repudiandae, incidunt quisquam. Soluta tenetur rem deleniti hic molestiae asperiores facilis nam recusandae veniam maxime, corporis quidem culpa odit, neque mollitia, doloribus vel delectus doloremque amet! Mollitia corporis libero a eum temporibus, earum assumenda iusto, ex itaque aut molestiae incidunt excepturi quos sequi provident, adipisci totam corrupti quasi reiciendis quisquam ut accusamus dolorum pariatur? Tenetur repellat porro officia. Consequuntur doloremque, error sequi minima aspernatur dolor vero ad deserunt, quisquam tenetur laudantium nulla at quos sunt quidem repudiandae voluptatum. Vel voluptatum sapiente corporis ipsa sunt, veniam odio nostrum excepturi fuga aspernatur ipsum itaque! Dolor eius eum, labore voluptate nulla nihil aliquid placeat enim tempore soluta maxime inventore illum nostrum? Commodi ut magnam laudantium doloribus enim fugiat alias vero. Dolorem quasi architecto tenetur, aperiam neque, velit ab quod sunt debitis laborum ipsum dignissimos sed? Itaque delectus aspernatur veniam voluptates sunt accusantium pariatur hic, iusto laudantium accusamus ratione quam, nulla quo mollitia, incidunt deleniti. Explicabo ipsum similique quis nisi incidunt laborum vero cum dolore eos et quo quasi ad voluptatibus, sunt reprehenderit odit provident asperiores perspiciatis consequatur, aut alias molestiae cumque rem error? Esse sint iste earum, maiores veritatis incidunt officiis delectus vero voluptatibus deleniti culpa?
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quae a id ratione reprehenderit eos corporis dolorum illum libero, commodi ducimus quo? Ut nesciunt perferendis alias esse pariatur nisi autem dicta velit dolor nam hic distinctio aperiam officiis enim, tempora, ratione quae voluptas voluptatum reiciendis! Commodi provident ratione nihil nesciunt unde, culpa nam vitae excepturi doloremque, distinctio numquam sint et fugiat voluptate blanditiis. Omnis earum distinctio animi accusantium sit, eum quae quibusdam, quam magnam, itaque obcaecati fugiat! Dolore repellat totam, iste laborum odit dolores esse, nostrum tempora doloremque quas ipsam debitis nam sunt commodi cupiditate molestiae consectetur rem, omnis voluptates deleniti ea asperiores? Tenetur vel repellendus enim porro repudiandae, incidunt quisquam. Soluta tenetur rem deleniti hic molestiae asperiores facilis nam recusandae veniam maxime, corporis quidem culpa odit, neque mollitia, doloribus vel delectus doloremque amet! Mollitia corporis libero a eum temporibus, earum assumenda iusto, ex itaque aut molestiae incidunt excepturi quos sequi provident, adipisci totam corrupti quasi reiciendis quisquam ut accusamus dolorum pariatur? Tenetur repellat porro officia. Consequuntur doloremque, error sequi minima aspernatur dolor vero ad deserunt, quisquam tenetur laudantium nulla at quos sunt quidem repudiandae voluptatum. Vel voluptatum sapiente corporis ipsa sunt, veniam odio nostrum excepturi fuga aspernatur ipsum itaque! Dolor eius eum, labore voluptate nulla nihil aliquid placeat enim tempore soluta maxime inventore illum nostrum? Commodi ut magnam laudantium doloribus enim fugiat alias vero. Dolorem quasi architecto tenetur, aperiam neque, velit ab quod sunt debitis laborum ipsum dignissimos sed? Itaque delectus aspernatur veniam voluptates sunt accusantium pariatur hic, iusto laudantium accusamus ratione quam, nulla quo mollitia, incidunt deleniti. Explicabo ipsum similique quis nisi incidunt laborum vero cum dolore eos et quo quasi ad voluptatibus, sunt reprehenderit odit provident asperiores perspiciatis consequatur, aut alias molestiae cumque rem error? Esse sint iste earum, maiores veritatis incidunt officiis delectus vero voluptatibus deleniti culpa?
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quae a id ratione reprehenderit eos corporis dolorum illum libero, commodi ducimus quo? Ut nesciunt perferendis alias esse pariatur nisi autem dicta velit dolor nam hic distinctio aperiam officiis enim, tempora, ratione quae voluptas voluptatum reiciendis! Commodi provident ratione nihil nesciunt unde, culpa nam vitae excepturi doloremque, distinctio numquam sint et fugiat voluptate blanditiis. Omnis earum distinctio animi accusantium sit, eum quae quibusdam, quam magnam, itaque obcaecati fugiat! Dolore repellat totam, iste laborum odit dolores esse, nostrum tempora doloremque quas ipsam debitis nam sunt commodi cupiditate molestiae consectetur rem, omnis voluptates deleniti ea asperiores? Tenetur vel repellendus enim porro repudiandae, incidunt quisquam. Soluta tenetur rem deleniti hic molestiae asperiores facilis nam recusandae veniam maxime, corporis quidem culpa odit, neque mollitia, doloribus vel delectus doloremque amet! Mollitia corporis libero a eum temporibus, earum assumenda iusto, ex itaque aut molestiae incidunt excepturi quos sequi provident, adipisci totam corrupti quasi reiciendis quisquam ut accusamus dolorum pariatur? Tenetur repellat porro officia. Consequuntur doloremque, error sequi minima aspernatur dolor vero ad deserunt, quisquam tenetur laudantium nulla at quos sunt quidem repudiandae voluptatum. Vel voluptatum sapiente corporis ipsa sunt, veniam odio nostrum excepturi fuga aspernatur ipsum itaque! Dolor eius eum, labore voluptate nulla nihil aliquid placeat enim tempore soluta maxime inventore illum nostrum? Commodi ut magnam laudantium doloribus enim fugiat alias vero. Dolorem quasi architecto tenetur, aperiam neque, velit ab quod sunt debitis laborum ipsum dignissimos sed? Itaque delectus aspernatur veniam voluptates sunt accusantium pariatur hic, iusto laudantium accusamus ratione quam, nulla quo mollitia, incidunt deleniti. Explicabo ipsum similique quis nisi incidunt laborum vero cum dolore eos et quo quasi ad voluptatibus, sunt reprehenderit odit provident asperiores perspiciatis consequatur, aut alias molestiae cumque rem error? Esse sint iste earum, maiores veritatis incidunt officiis delectus vero voluptatibus deleniti culpa?
            </div> */}
            <div className='text-2xl rounded-[30px] rounded-br-none p-3 px-6 text-white font-bold bg-[#b4ba3a] w-fit self-end'>
                Hello
            </div>
            <div className='text-2xl rounded-[30px] rounded-bl-none p-3 px-6 text-white font-bold bg-[#696d1e] w-fit'>
                Hi there
            </div>
            <div className="text-2xl is_typing_container">
                typing 
                <span className="typing-dot dot1">.</span>
                <span className="typing-dot dot2">.</span>
                <span className="typing-dot dot3">.</span>
            </div>
            
        </div>
        <div className="typing absolute bottom-0 w-full bg-gradient-to-tl to-[#cfad1f] from-[#93a877] flex p-7 items-center justify-center text-white gap-10 h-[130px] align-start">
            <input type="text" className='p-4 w-3/5 rounded-[30px]' placeholder='Write a message...' />
            <div className='font-bold text-2xl'>Send</div>
        </div>
    </div>
  );
};

export default MessageBox;
